package http

import "go.mongodb.org/mongo-driver/bson/primitive"

// Group represents the structure of a group in the application
type Group struct {

	// Id is the unique identifier for the group, automatically generated by MongoDB.
	Id 					primitive.ObjectID 		`json:"id" bson:"_id,omitempty"`

	// GroupOwnerId is the unique identifier of the user who owns the group.
	// The `validate:"required"` tag ensures that this field must be provided when creating a group.
	GroupOwnerId		primitive.ObjectID		`json:"groupOwnerId" bson:"_groupOwnerId" validate:"required"`

	// GroupMemberIds is a slice of ObjectIDs representing the members of the group.
	// This field can be empty initially and will be populated as members are added.
	GroupMemberIds 		[]primitive.ObjectID 	`json:"groupMemberIds" bson:"_groupMemberIds"`

	// GroupName is the name of the group.
	// The `validate:"required,min=8,max=100"` tag ensures that the name must be provided and must have a length between 8 and 100 characters.
	GroupName 			string 					`json:"groupName" bson:"groupName" validate:"required,min=8,max=100"`

	// GroupImageHash is a hash or reference to the group's profile image.
	// The `validate:"required"` tag ensures that an image hash must be provided.
	GroupImageHash 		string 					`json:"groupImageHash" bson:"groupImageHash" validate:"required"`

	// GroupDescription provides additional details about the group.
	// The `validate:"required,min=8,max=255"` tag ensures that the description must be provided with a length between 8 and 255 characters.
	GroupDescription 	string 					`json:"groupDescription" bson:"groupDescription" validate:"required,min=8,max=255"`

}