package http

import "go.mongodb.org/mongo-driver/bson/primitive"

// Proposal represents the structure of a proposal in the application.
type Proposal struct {

	// Id is the unique identifier for the proposal, automatically generated by MongoDB.
	Id 					primitive.ObjectID 			`json:"id" bson:"_id,omitempty"`

	// PostId is the unique identifier of the post associated with the proposal.
	// The `validate:"required"` tag ensures this field must be provided when creating a proposal.
	PostId 				primitive.ObjectID 			`json:"postId" bson:"_postId" validate:"required"`

	// CreatorId is the unique identifier of the user who created the proposal.
	// The `validate:"required"` tag ensures this field must be provided when creating a proposal.
	CreatorId 			primitive.ObjectID 			`json:"creatorId" bson:"_creatorId" validate:"required"`

	// BuyerId is the unique identifier of the buyer associated with the proposal.
	// The `validate:"required"` tag ensures this field must be provided when creating a proposal.
	BuyerId 			primitive.ObjectID 			`json:"buyerId" bson:"_buyerId" validate:"required"`

	// FileHash is a hash or reference to the file associated with the proposal.
	// The `validate:"required"` tag ensures this field must be provided when creating a proposal.
	FileHash 			string 						`json:"fileHash" bson:"fileHash" validate:"required"`

	// FinalFee is the final agreed fee for the proposal.
	// The `validate:"required,min=0"` tag ensures this field must be provided and must be a non-negative value.
	FinalFee 			float64 					`json:"finalFee" bson:"finalFee" validate:"required,min=0"`

	// DaysToComplete specifies the number of days required to complete the task/job.
	// The `validate:"required"` tag ensures this field must be provided when creating a proposal.
	DaysToComplete 		uint64 						`json:"daysToComplete" bson:"daysToComplete" validate:"required"`

	// AcceptByBuyer indicates whether the buyer has accepted the proposal.
	// The `validate:"isFalse"` tag ensures this field must be set to false during creation.
	AcceptByBuyer 		bool 						`json:"acceptByBuyer" bson:"acceptByBuyer" validate:"isFalse"`
}
